title: Edison Frade - Advocacia
description: Advogado portuguÃªs-brasileiro especializado em Nacionalidade, Penal, Criminal e Direito Familiar
url: https://edisonfradeadv.github.io/site
theme: jekyll-theme-cayman
show_downloads: false
